// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PickleHub.Notification.Infrastructure.Persistence;

#nullable disable

namespace PickleHub.Notification.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260724074050_InitialNotificationDb")]
    partial class InitialNotificationDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PickleHub.Notification.Domain.Entities.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ToEmail", "Status")
                        .HasDatabaseName("idx_email_logs_to_status");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("PickleHub.Notification.Domain.Entities.NotificationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("NotificationTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BodyHtml = "\n<div style=\"font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden;\">\n    <div style=\"background-color: #1a56db; color: #ffffff; padding: 20px; text-align: center;\">\n        <h1 style=\"margin: 0; font-size: 24px;\">PickleHub Store</h1>\n        <p style=\"margin: 5px 0 0 0; font-size: 14px;\">Xác nhận đơn hàng thành công</p>\n    </div>\n    <div style=\"padding: 20px;\">\n        <p>Xin chào <strong>{{CustomerName}}</strong>,</p>\n        <p>Cảm ơn bạn đã đặt hàng tại PickleHub! Đơn hàng <strong>#{{OrderCode}}</strong> của bạn đã được ghi nhận và đang chờ xử lý.</p>\n        \n        <table style=\"width: 100%; border-collapse: collapse; margin: 20px 0;\">\n            <tr style=\"background-color: #f8f9fa;\">\n                <th style=\"padding: 10px; border: 1px solid #dee2e6; text-align: left;\">M đơn hng</th>\n                <td style=\"padding: 10px; border: 1px solid #dee2e6;\">#{{OrderCode}}</td>\n            </tr>\n            <tr>\n                <th style=\"padding: 10px; border: 1px solid #dee2e6; text-align: left;\">T?ng gi? tr?</th>\n                <td style=\"padding: 10px; border: 1px solid #dee2e6; color: #1a56db; font-weight: bold;\">{{TotalAmount}} VN</td>\n            </tr>\n            <tr style=\"background-color: #f8f9fa;\">\n                <th style=\"padding: 10px; border: 1px solid #dee2e6; text-align: left;\">?a ch? giao hng</th>\n                <td style=\"padding: 10px; border: 1px solid #dee2e6;\">{{ShippingAddress}}</td>\n            </tr>\n        </table>\n        \n        <p>Chng ti s? thng bo cho b?n ngay khi don hng b?t d?u du?c v?n chuy?n.</p>\n    </div>\n    <div style=\"background-color: #f8f9fa; padding: 15px; text-align: center; font-size: 12px; color: #6c757d;\">\n        &copy; 2026 PickleHub Store. M?i quy?n du?c b?o luu.\n    </div>\n</div>",
                            Name = "OrderConfirmation",
                            Subject = "[PickleHub] Xc nh?n don hng #{{OrderCode}}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            BodyHtml = "\n<div style=\"font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden;\">\n    <div style=\"background-color: #16a34a; color: #ffffff; padding: 20px; text-align: center;\">\n        <h1 style=\"margin: 0; font-size: 24px;\">PickleHub Store</h1>\n        <p style=\"margin: 5px 0 0 0; font-size: 14px;\">Xác nhận thanh toán thành công</p>\n    </div>\n    <div style=\"padding: 20px;\">\n        <p>Xin chào <strong>{{CustomerName}}</strong>,</p>\n        <p>Hệ thống đã nhận được thanh toán cho đơn hàng <strong>#{{OrderCode}}</strong> qua phương thức <strong>{{PaymentMethod}}</strong>.</p>\n        \n        <div style=\"background-color: #f0fdf4; border-left: 4px solid #16a34a; padding: 15px; margin: 20px 0;\">\n            <p style=\"margin: 0; color: #15803d; font-weight: bold;\">Số tiền đã thanh toán: {{Amount}} VN</p>\n            <p style=\"margin: 5px 0 0 0; font-size: 13px; color: #166534;\">Đơn hàng của bạn đang được chuẩn bị để đóng gói và vận chuyển.</p>\n        </div>\n    </div>\n    <div style=\"background-color: #f8f9fa; padding: 15px; text-align: center; font-size: 12px; color: #6c757d;\">\n        &copy; 2026 PickleHub Store. Mọi quyền được bảo lưu.\n    </div>\n</div>",
                            Name = "PaymentSuccess",
                            Subject = "[PickleHub] Xác nhận thanh toán đơn hàng #{{OrderCode}} thành công",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            BodyHtml = "\n<div style=\"font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden;\">\n    <div style=\"background-color: #2563eb; color: #ffffff; padding: 20px; text-align: center;\">\n        <h1 style=\"margin: 0; font-size: 24px;\">PickleHub Store</h1>\n        <p style=\"margin: 5px 0 0 0; font-size: 14px;\">Trạng thái đơn hàng đã thay đổi</p>\n    </div>\n    <div style=\"padding: 20px;\">\n        <p>Xin chào <strong>{{CustomerName}}</strong>,</p>\n        <p>Đơn hàng <strong>#{{OrderCode}}</strong> của bạn vừa được chuyển sang trạng thái: <strong style=\"color: #2563eb;\">{{OrderStatusName}}</strong>.</p>\n        \n        <p>Mã vận đơn: <strong>{{TrackingNumber}}</strong></p>\n        <p>Bạn có thể theo dõi hành trình giao hàng bằng cách bấm vào nút bên dưới:</p>\n        \n        <div style=\"text-align: center; margin: 25px 0;\">\n            <a href=\"{{TrackingUrl}}\" style=\"background-color: #2563eb; color: #ffffff; text-decoration: none; padding: 12px 24px; border-radius: 6px; font-weight: bold; display: inline-block;\">Theo dõi vận đơn</a>\n        </div>\n    </div>\n    <div style=\"background-color: #f8f9fa; padding: 15px; text-align: center; font-size: 12px; color: #6c757d;\">\n        &copy; 2026 PickleHub Store. M?i quy?n du?c b?o luu.\n    </div>\n</div>",
                            Name = "OrderStatusUpdated",
                            Subject = "[PickleHub] Cập nhật trạng thái đơn hàng #{{OrderCode}}",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Version = 1
                        });
                });

            modelBuilder.Entity("PickleHub.Notification.Domain.Entities.ProcessedEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId");

                    b.ToTable("ProcessedEvents");
                });

            modelBuilder.Entity("PickleHub.Notification.Domain.Entities.UserNotificationSetting", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("OrderNotiEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("PaymentNotiEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("PromotionEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("SystemNotiEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("WebEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("UserNotificationSettings");
                });

            modelBuilder.Entity("PickleHub.Notification.Domain.Entities.WebNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("VIEW_ORDER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("idx_web_notifications_user_read");

                    b.ToTable("WebNotifications");
                });
#pragma warning restore 612, 618
        }
    }
}
