// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PickleHub.Customers.Infrastructure.Persistence;

#nullable disable

namespace PickleHub.Customers.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    partial class CustomerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PickleHub.Customers.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalSpent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_spent");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("PickleHub.Customers.Domain.Entities.CustomerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("customer_address", (string)null);
                });

            modelBuilder.Entity("PickleHub.Customers.Domain.Entities.CustomerSpendLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("customer_spend_ledger", (string)null);
                });

            modelBuilder.Entity("PickleHub.Customers.Domain.Entities.LoyaltyTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BenefitsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("[]")
                        .HasColumnName("benefits_json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount_percent");

                    b.Property<decimal>("MinSpend")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("min_spend");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("loyalty_tier", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            BenefitsJson = "[\"\\u01AFu \\u0111\\u00E3i \\u0111\\u1EB7c quy\\u1EC1n trong c\\u00E1c d\\u1ECBp sinh nh\\u1EADt, ra m\\u1EAFt s\\u1EA3n ph\\u1EA9m m\\u1EDBi v\\u00E0 nh\\u1EEFng s\\u1EF1 ki\\u1EC7n kh\\u00E1c.\",\"H\\u1ED7 tr\\u1EE3 ch\\u0103m s\\u00F3c t\\u1EADn t\\u00ECnh trong su\\u1ED1t qu\\u00E1 tr\\u00ECnh mua h\\u00E0ng.\"]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercent = 5m,
                            MinSpend = 3000000m,
                            Name = "Rookie",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            BenefitsJson = "[\"\\u01AFu \\u0111\\u00E3i \\u0111\\u1EB7c quy\\u1EC1n trong c\\u00E1c d\\u1ECBp sinh nh\\u1EADt, ra m\\u1EAFt s\\u1EA3n ph\\u1EA9m m\\u1EDBi v\\u00E0 nh\\u1EEFng s\\u1EF1 ki\\u1EC7n kh\\u00E1c.\",\"H\\u1ED7 tr\\u1EE3 ch\\u0103m s\\u00F3c t\\u1EADn t\\u00ECnh trong su\\u1ED1t qu\\u00E1 tr\\u00ECnh mua h\\u00E0ng.\"]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercent = 7m,
                            MinSpend = 8000000m,
                            Name = "Rally",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            BenefitsJson = "[\"\\u01AFu \\u0111\\u00E3i \\u0111\\u1EB7c quy\\u1EC1n trong c\\u00E1c d\\u1ECBp sinh nh\\u1EADt, ra m\\u1EAFt s\\u1EA3n ph\\u1EA9m m\\u1EDBi v\\u00E0 nh\\u1EEFng s\\u1EF1 ki\\u1EC7n kh\\u00E1c.\",\"H\\u1ED7 tr\\u1EE3 ch\\u0103m s\\u00F3c t\\u1EADn t\\u00ECnh trong su\\u1ED1t qu\\u00E1 tr\\u00ECnh mua h\\u00E0ng.\"]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercent = 10m,
                            MinSpend = 20000000m,
                            Name = "Ace",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            BenefitsJson = "[\"\\u01AFu \\u0111\\u00E3i \\u0111\\u1EB7c quy\\u1EC1n trong c\\u00E1c d\\u1ECBp sinh nh\\u1EADt, ra m\\u1EAFt s\\u1EA3n ph\\u1EA9m m\\u1EDBi v\\u00E0 nh\\u1EEFng s\\u1EF1 ki\\u1EC7n kh\\u00E1c.\",\"H\\u1ED7 tr\\u1EE3 ch\\u0103m s\\u00F3c t\\u1EADn t\\u00ECnh trong su\\u1ED1t qu\\u00E1 tr\\u00ECnh mua h\\u00E0ng.\"]",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercent = 15m,
                            MinSpend = 50000000m,
                            Name = "Champion",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("PickleHub.Customers.Domain.Entities.CustomerAddress", b =>
                {
                    b.HasOne("PickleHub.Customers.Domain.Entities.Customer", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PickleHub.Customers.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
